DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS grades;
DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS terms;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS students_history;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS departments;

