// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lin-snow/edumgr/internal/config"
	"github.com/lin-snow/edumgr/internal/handler"
	"github.com/lin-snow/edumgr/internal/repository"
	"github.com/lin-snow/edumgr/internal/server"
	"github.com/lin-snow/edumgr/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeHandlers creates all handlers with dependency injection
func InitializeHandlers(db *gorm.DB, cfg config.Config) (*server.Handlers, error) {
	healthHandler := handler.NewHealthHandler()
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(userRepository, cfg)
	authHandler := handler.NewAuthHandler(authService, cfg)
	departmentRepository := repository.NewDepartmentRepository(db)
	departmentService := service.NewDepartmentService(departmentRepository)
	departmentHandler := handler.NewDepartmentHandler(departmentService)
	studentRepository := repository.NewStudentRepository(db)
	studentService := service.NewStudentService(studentRepository, userRepository, db)
	studentHandler := handler.NewStudentHandler(studentService)
	staffRepository := repository.NewStaffRepository(db)
	staffService := service.NewStaffService(staffRepository)
	staffHandler := handler.NewStaffHandler(staffService)
	courseRepository := repository.NewCourseRepository(db)
	courseService := service.NewCourseService(courseRepository)
	courseHandler := handler.NewCourseHandler(courseService)
	termRepository := repository.NewTermRepository(db)
	termService := service.NewTermService(termRepository)
	termHandler := handler.NewTermHandler(termService)
	enrollmentRepository := repository.NewEnrollmentRepository(db)
	enrollmentService := service.NewEnrollmentService(enrollmentRepository, termRepository, courseRepository, studentRepository, userRepository, db)
	enrollmentHandler := handler.NewEnrollmentHandler(enrollmentService)
	gradeRepository := repository.NewGradeRepository(db)
	gradeService := service.NewGradeService(gradeRepository, courseRepository, studentRepository, userRepository, staffRepository, db)
	gradeHandler := handler.NewGradeHandler(gradeService)
	reportRepository := repository.NewReportRepository(db)
	reportService := service.NewReportService(reportRepository)
	reportHandler := handler.NewReportHandler(reportService)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	handlers := server.NewHandlers(healthHandler, authHandler, departmentHandler, studentHandler, staffHandler, courseHandler, termHandler, enrollmentHandler, gradeHandler, reportHandler, userHandler)
	return handlers, nil
}
